// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: twitch/v1/twitch.proto

package twitchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrentUserInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCurrentUserInfoRequest) Reset() {
	*x = GetCurrentUserInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twitch_v1_twitch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurrentUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserInfoRequest) ProtoMessage() {}

func (x *GetCurrentUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_twitch_v1_twitch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_twitch_v1_twitch_proto_rawDescGZIP(), []int{0}
}

type GetCurrentUserInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *TwitchUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *GetCurrentUserInfoResponse) Reset() {
	*x = GetCurrentUserInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twitch_v1_twitch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurrentUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserInfoResponse) ProtoMessage() {}

func (x *GetCurrentUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twitch_v1_twitch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_twitch_v1_twitch_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentUserInfoResponse) GetUser() *TwitchUser {
	if x != nil {
		return x.User
	}
	return nil
}

var File_twitch_v1_twitch_proto protoreflect.FileDescriptor

var file_twitch_v1_twitch_proto_rawDesc = []byte{
	0x0a, 0x16, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x77, 0x69, 0x74,
	0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68,
	0x2e, 0x76, 0x31, 0x1a, 0x16, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1b, 0x0a, 0x19, 0x47,
	0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x47, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x43,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x77, 0x69, 0x74, 0x63, 0x68, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x32, 0x74, 0x0a, 0x0d, 0x54, 0x77, 0x69, 0x74, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x63, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x63,
	0x68, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6c, 0x6c, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x64, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2f, 0x76, 0x31, 0x3b,
	0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_twitch_v1_twitch_proto_rawDescOnce sync.Once
	file_twitch_v1_twitch_proto_rawDescData = file_twitch_v1_twitch_proto_rawDesc
)

func file_twitch_v1_twitch_proto_rawDescGZIP() []byte {
	file_twitch_v1_twitch_proto_rawDescOnce.Do(func() {
		file_twitch_v1_twitch_proto_rawDescData = protoimpl.X.CompressGZIP(file_twitch_v1_twitch_proto_rawDescData)
	})
	return file_twitch_v1_twitch_proto_rawDescData
}

var file_twitch_v1_twitch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_twitch_v1_twitch_proto_goTypes = []interface{}{
	(*GetCurrentUserInfoRequest)(nil),  // 0: twitch.v1.GetCurrentUserInfoRequest
	(*GetCurrentUserInfoResponse)(nil), // 1: twitch.v1.GetCurrentUserInfoResponse
	(*TwitchUser)(nil),                 // 2: twitch.v1.TwitchUser
}
var file_twitch_v1_twitch_proto_depIdxs = []int32{
	2, // 0: twitch.v1.GetCurrentUserInfoResponse.user:type_name -> twitch.v1.TwitchUser
	0, // 1: twitch.v1.TwitchService.GetCurrentUserInfo:input_type -> twitch.v1.GetCurrentUserInfoRequest
	1, // 2: twitch.v1.TwitchService.GetCurrentUserInfo:output_type -> twitch.v1.GetCurrentUserInfoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_twitch_v1_twitch_proto_init() }
func file_twitch_v1_twitch_proto_init() {
	if File_twitch_v1_twitch_proto != nil {
		return
	}
	file_twitch_v1_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_twitch_v1_twitch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCurrentUserInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_twitch_v1_twitch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCurrentUserInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_twitch_v1_twitch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_twitch_v1_twitch_proto_goTypes,
		DependencyIndexes: file_twitch_v1_twitch_proto_depIdxs,
		MessageInfos:      file_twitch_v1_twitch_proto_msgTypes,
	}.Build()
	File_twitch_v1_twitch_proto = out.File
	file_twitch_v1_twitch_proto_rawDesc = nil
	file_twitch_v1_twitch_proto_goTypes = nil
	file_twitch_v1_twitch_proto_depIdxs = nil
}
